-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.67.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 21/03/2014 19:58:09
-- Server version: 5.5.8-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE adm_personal_places;

--
-- Definition for table countries
--
DROP TABLE IF EXISTS countries;
CREATE TABLE countries (
  iso2 VARCHAR(2) NOT NULL,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (iso2)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 67
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table users
--
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user VARCHAR(20) NOT NULL,
  pass VARCHAR(20) NOT NULL,
  name VARCHAR(50) NOT NULL,
  gender VARCHAR(2) NOT NULL,
  email VARCHAR(50) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  country_iso2 VARCHAR(2) NOT NULL,
  photo_uri VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX FK_users_country (country_iso2),
  UNIQUE INDEX UK_users_email (email),
  UNIQUE INDEX UK_users_user (user),
  CONSTRAINT FK_users_country FOREIGN KEY (country_iso2)
    REFERENCES countries(iso2) ON DELETE RESTRICT ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 44
AVG_ROW_LENGTH = 4096
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table friendship
--
DROP TABLE IF EXISTS friendship;
CREATE TABLE friendship (
  user1_id INT(11) NOT NULL,
  user2_id INT(11) NOT NULL,
  INDEX FK_friendship_user2 (user2_id),
  UNIQUE INDEX UK_friendship (user1_id, user2_id),
  CONSTRAINT FK_friendship_user1 FOREIGN KEY (user1_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_friendship_user2 FOREIGN KEY (user2_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table shares
--
DROP TABLE IF EXISTS shares;
CREATE TABLE shares (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_from INT(11) DEFAULT NULL,
  user_to INT(11) NOT NULL,
  content TEXT NOT NULL,
  PRIMARY KEY (id),
  INDEX FK_shares_user_from (user_from),
  INDEX FK_shares_user_to (user_to),
  CONSTRAINT FK_shares_user_from FOREIGN KEY (user_from)
    REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT FK_shares_user_to FOREIGN KEY (user_to)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table countries
--
INSERT INTO countries VALUES 
  ('AD', 'Andorra'),
  ('AE', 'Emiratos Árabes Unidos'),
  ('AF', 'Afganistán'),
  ('AG', 'Antigua y Barbuda'),
  ('AI', 'Anguila'),
  ('AL', 'Albania'),
  ('AM', 'Armenia'),
  ('AN', 'Antillas Neerlandesas'),
  ('AO', 'Angola'),
  ('AQ', 'Antártida'),
  ('AR', 'Argentina'),
  ('AS', 'Samoa americana'),
  ('AT', 'Austria'),
  ('AU', 'Australia'),
  ('AW', 'Aruba'),
  ('AX', 'Islas Aland'),
  ('AZ', 'Azerbaiyán'),
  ('BA', 'Bosnia y Hercegovina'),
  ('BB', 'Barbados'),
  ('BD', 'Bangladesh'),
  ('BE', 'Bélgica'),
  ('BF', 'Burkina Faso'),
  ('BG', 'Bulgaria'),
  ('BH', 'Bahráin'),
  ('BI', 'Burundi'),
  ('BJ', 'Benín'),
  ('BM', 'Bermudas'),
  ('BN', 'Brunéi'),
  ('BO', 'Bolivia'),
  ('BR', 'Brasil'),
  ('BS', 'Bahamas'),
  ('BT', 'Bután'),
  ('BV', 'Isla Bouvet'),
  ('BW', 'Botsuana'),
  ('BY', 'Bielorrusia'),
  ('BZ', 'Belice'),
  ('CA', 'Canadá'),
  ('CC', 'Islas Cocos'),
  ('CD', 'República Democrática del Congo'),
  ('CF', 'República Centroafricana'),
  ('CG', 'República del Congo'),
  ('CH', 'Suiza'),
  ('CI', 'Costa de Marfil'),
  ('CK', 'Islas Cook'),
  ('CL', 'Chile'),
  ('CM', 'Camerún'),
  ('CN', 'China'),
  ('CO', 'Colombia'),
  ('CR', 'Costa Rica'),
  ('CU', 'Cuba'),
  ('CV', 'Cabo Verde'),
  ('CX', 'Isla Christmas'),
  ('CY', 'Chipre'),
  ('CZ', 'República Checa'),
  ('DE', 'Alemania'),
  ('DJ', 'Yibuti'),
  ('DK', 'Dinamarca'),
  ('DM', 'Dominica'),
  ('DO', 'República Dominicana'),
  ('DZ', 'Argelia'),
  ('EC', 'Ecuador'),
  ('EE', 'Estonia'),
  ('EG', 'Egipto'),
  ('EH', 'Sáhara Occidental'),
  ('ER', 'Eritrea'),
  ('ES', 'España'),
  ('ET', 'Etiopía'),
  ('FI', 'Finlandia'),
  ('FJ', 'Fiyi'),
  ('FK', 'Islas Malvinas'),
  ('FM', 'Micronesia'),
  ('FO', 'Islas Feroe'),
  ('FR', 'Francia'),
  ('GA', 'Gabón'),
  ('GB', 'Reino Unido'),
  ('GD', 'Granada'),
  ('GE', 'Georgia'),
  ('GF', 'Guayana Francesa'),
  ('GG', 'Guernsey'),
  ('GH', 'Ghana'),
  ('GI', 'Gibraltar'),
  ('GL', 'Groenlandia'),
  ('GM', 'Gambia'),
  ('GN', 'Guinea'),
  ('GP', 'Guadalupe'),
  ('GQ', 'Guinea Ecuatorial'),
  ('GR', 'Grecia'),
  ('GS', 'Islas Georgia del Sur y Sandwich del Sur'),
  ('GT', 'Guatemala'),
  ('GU', 'Guam'),
  ('GW', 'Guinea-Bissau'),
  ('GY', 'Guyana'),
  ('HK', 'Hong Kong'),
  ('HM', 'Islas Heard y McDonald'),
  ('HN', 'Honduras'),
  ('HR', 'Croacia'),
  ('HT', 'Haití'),
  ('HU', 'Hungría'),
  ('ID', 'Indonesia'),
  ('IE', 'Irlanda'),
  ('IL', 'Israel'),
  ('IM', 'Isla de Man'),
  ('IN', 'La India'),
  ('IO', 'Territorio Británico del Océano Índico'),
  ('IQ', 'Iraq'),
  ('IR', 'Irán'),
  ('IS', 'Islandia'),
  ('IT', 'Italia'),
  ('JE', 'Jersey'),
  ('JM', 'Jamaica'),
  ('JO', 'Jordania'),
  ('JP', 'Japón'),
  ('KE', 'Kenia'),
  ('KG', 'Kirguizistán'),
  ('KH', 'Camboya'),
  ('KI', 'Kiribati'),
  ('KM', 'Comoras'),
  ('KN', 'San Cristóbal y Nieves'),
  ('KP', 'Corea del Norte'),
  ('KR', 'Corea del Sur'),
  ('KW', 'Kuwait'),
  ('KY', 'Islas Caimán'),
  ('KZ', 'Kazajistán'),
  ('LA', 'Laos'),
  ('LB', 'Líbano'),
  ('LC', 'Santa Lucía'),
  ('LI', 'Liechtenstein'),
  ('LK', 'Sri Lanka'),
  ('LR', 'Liberia'),
  ('LS', 'Lesoto'),
  ('LT', 'Lituania'),
  ('LU', 'Luxemburgo'),
  ('LV', 'Letonia'),
  ('LY', 'Libia'),
  ('MA', 'Marruecos'),
  ('MC', 'Mónaco'),
  ('MD', 'Moldavia'),
  ('ME', 'Montenegro'),
  ('MG', 'Madagascar'),
  ('MH', 'Islas Marshall'),
  ('MK', 'Macedonia'),
  ('ML', 'Mali'),
  ('MM', 'Myanmar'),
  ('MN', 'Mongolia'),
  ('MO', 'Macao'),
  ('MP', 'Islas Mariana del Norte'),
  ('MQ', 'Martinica'),
  ('MR', 'Mauritania'),
  ('MS', 'Montserrat'),
  ('MT', 'Malta'),
  ('MU', 'Mauricio'),
  ('MV', 'Maldivas'),
  ('MW', 'Malaui'),
  ('MX', 'México'),
  ('MY', 'Malasia'),
  ('MZ', 'Mozambique'),
  ('NA', 'Namibia'),
  ('NC', 'Nueva Caledonia'),
  ('NE', 'Níger'),
  ('NF', 'Isla Norfolk'),
  ('NG', 'Nigeria'),
  ('NI', 'Nicaragua'),
  ('NL', 'Países Bajos'),
  ('NO', 'Noruega'),
  ('NP', 'Nepal'),
  ('NR', 'Nauru'),
  ('NU', 'Niue'),
  ('NZ', 'Nueva Zelanda'),
  ('OM', 'Omán'),
  ('PA', 'Panamá'),
  ('PE', 'Perú'),
  ('PF', 'Polinesia Francesa'),
  ('PG', 'Papúa-Nueva Guinea'),
  ('PH', 'Filipinas'),
  ('PK', 'Pakistán'),
  ('PL', 'Polonia'),
  ('PM', 'San Pedro y Miquelón'),
  ('PN', 'Islas Pitcairn'),
  ('PR', 'Puerto Rico'),
  ('PS', 'Territorio Palestino'),
  ('PT', 'Portugal'),
  ('PW', 'Palaos'),
  ('PY', 'Paraguay'),
  ('QA', 'Qatar'),
  ('RE', 'Reunión'),
  ('RO', 'Rumania'),
  ('RS', 'Serbia'),
  ('RU', 'Rusia'),
  ('RW', 'Ruanda'),
  ('SA', 'Arabia Saudí'),
  ('SB', 'Islas Salomón'),
  ('SC', 'Seychelles'),
  ('SD', 'Sudán'),
  ('SE', 'Suecia'),
  ('SG', 'Singapur'),
  ('SH', 'Santa Elena'),
  ('SI', 'Eslovenia'),
  ('SJ', 'Islas Svalbard y Jan Mayen'),
  ('SK', 'Eslovaquia'),
  ('SL', 'Sierra Leona'),
  ('SM', 'San Marino'),
  ('SN', 'Senegal'),
  ('SO', 'Somalia'),
  ('SR', 'Surinam'),
  ('ST', 'Santo Tomé y Príncipe'),
  ('SV', 'El Salvador'),
  ('SY', 'Siria'),
  ('SZ', 'Suazilandia'),
  ('TC', 'Islas Turcas y Caicos'),
  ('TD', 'Chad'),
  ('TF', 'Territorios Australes Franceses'),
  ('TG', 'Togo'),
  ('TH', 'Tailandia'),
  ('TJ', 'Tayikistán'),
  ('TK', 'Tokelau'),
  ('TL', 'Timor Oriental'),
  ('TM', 'Turkmenistán'),
  ('TN', 'Túnez'),
  ('TO', 'Tonga'),
  ('TR', 'Turquía'),
  ('TT', 'Trinidad y Tobago'),
  ('TV', 'Tuvalu'),
  ('TW', 'Taiwán'),
  ('TZ', 'Tanzania'),
  ('UA', 'Ucrania'),
  ('UG', 'Uganda'),
  ('UM', 'Islas menores alejadas de los Estados Unidos'),
  ('US', 'Estados Unidos'),
  ('UY', 'Uruguay'),
  ('UZ', 'Uzbekistán'),
  ('VA', 'Ciudad del Vaticano'),
  ('VC', 'San Vicente y las Granadinas'),
  ('VE', 'Venezuela'),
  ('VG', 'Islas Vírgenes Británicas'),
  ('VI', 'Islas Vírgenes, EE.UU.'),
  ('VN', 'Vietnam'),
  ('VU', 'Vanuatu'),
  ('WF', 'Wallis y Futuna'),
  ('WS', 'Samoa'),
  ('YE', 'Yemen'),
  ('YT', 'Mayotte'),
  ('ZA', 'Sudáfrica'),
  ('ZM', 'Zambia'),
  ('ZW', 'Zimbabue');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES 
  (1, 'angel', 'valencia', 'Angel Hernández', 'M', 'angelherriv@yahoo.es', '692409239', 'ES', NULL),
  (4, 'tomas', 'madrid', 'Tomás Pérez', 'M', 'tomasperez@yahoo.es', '666777123', 'ES', NULL),
  (31, 'george', 'madrid', 'George Clooney', 'M', 'georgeclooney@yahoo.com', '666789123', 'ES', NULL),
  (35, 'joan', 'valencia', 'Joan Velilla', 'M', 'joanvetor@yahoo.com', '666777890', 'ES', NULL);

-- 
-- Dumping data for table friendship
--
-- Table adm_personal_places.friendship does not contain any data (it is empty)

-- 
-- Dumping data for table shares
--
-- Table adm_personal_places.shares does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;